### ISSUE TITLE
pypi download page doesn't include source distribution

### ISSUE THREAD

**Issue by isaac-hazy** [cloudflare/stpyv8#106]
If you go to https://pypi.org/project/stpyv8/#files there is no source distribution. 

This means a tool like Poetry can't fall back from wheel to source build if the target isn't available.

An example of when this will happen - a linux docker build run on an m1 mac will be manylinux arm, there's no wheel hosted and no source distribution.

There are ways around it, but the config becomes complicated so it would be better to have a source distribution available in pypi

**Comment by buffer** [comment]
No problem at all in publishing the source distribution as well. I will take care of the details and start publishing it from the next release. Thanks!
