### ISSUE TITLE
Can it support Inspector protocol?

### ISSUE THREAD

**Issue by Taiung** [cloudflare/stpyv8#110]
I want to debug when python executes js code. I checked some documents of V8, but I am not familiar with C++ and cannot implement this function myself. So, I would like to ask if this feature can be added in subsequent updates.

**Comment by buffer** [comment]
Can you further detail what you would be interested in? Not sure I figured that out. Thanks"

**Comment by Taiung** [comment]
For example, the v8Py library (https://github.com/tbodt/v8py/blob/master/v8py/devtools.py) provides a debugger function. With the help of V8’s Inspector, the executing js code can be debugged through ChromeDevtools. js code can also be understood as debugging js code in node. I'm not sure if it's easy to understand if I express it this way.

I think this is a very good feature. I am currently trying to learn from the debugger part of v8Py and want to implement it in STPyV8, but it may be very difficult for me.

**Comment by buffer** [comment]
One of the main STPyV8 design goals is to keep the code as simpler as possible and to support just key features to execute JavaScript code from Python. Introducing the debugger support would greatly increase the complexity of the project and would not add great value to the project, at least for our own purposes. BTW please feel free to submit some code and we will evaluate together if including that is worth doing. Thanks.
