### ISSUE TITLE
Life cycle of JSContext

### ISSUE THREAD

**Issue by stemillington-flock** [cloudflare/stpyv8#115]
I'm thinking of using STPyV8 as a way to share some small js functions between some python back end and js front end code.

Do I need to create a new JSContext for each function call or can I just get references to all the functions in one hit and reuse where required, in this case would i need to keep a reference to the JSContext?. Not sure how garbage collection might apply and whether i'd end up with dead references? Or is there no performance impact to just recreating the functions as and when needed?

**Comment by buffer** [comment]
You're not required to create a new context each time you invoke a function but can reuse it, if that makes sense for you of course. Please take a look at Thug [1] for an example of how to keep a reference to a context and reuse it all the times you need. FYI I am the lead developer of Thug (and STPyV8 was created for Thug in the first place) so if you need additional help just ask. Thanks! 

[1] https://github.com/buffer/thug
