### ISSUE TITLE
Python 3.13 support

### ISSUE THREAD

**Issue by stefan6419846** [cloudflare/stpyv8#118]
Python 3.13 is scheduled to be released in about two weeks, with the first release candidates being available since August (https://peps.python.org/pep-0719/#release-schedule).

For this reason, it would be great to start testing against Python 3.13 and providing official wheels for Python 3.13 to allow installing and using the package as usual once Python 3.13 has been released officially.

**Comment by buffer** [comment]
Python 3.13 will be supported for sure but we have to wait until Github runners support this version too. Reasonably this will happen a few weeks after the official release

**Comment by stefan6419846** [comment]
AFAIK GitHub Runners already support this for quite a while - at least when using the `setup-python` action by specifying `"3.13-dev"`. Initially, Python 3.13 would have been released this Monday, but has been postponed for a week as far as I am aware.
