### ISSUE TITLE
how to use multi thread?

### ISSUE THREAD

**Issue by RonaldinhoL** [cloudflare/stpyv8#26]
``` python
import STPyV8
import threading


class Global(STPyV8.JSContext):
    def log(self, *args):
        print(*args)

def run():
    with STPyV8.JSIsolate() as isolate:
        with STPyV8.JSContext(Global()) as ctx:
            # ctx.eval("""function log(){}""")
            ctx.eval("log(1+1)")


t1 = threading.Thread(target=run)
t1.start()
t2 = threading.Thread(target=run)
t2.start()
t1.join()
t2.join()
```

i got Process finished with exit code 11

**Comment by RonaldinhoL** [comment]
case in test_Multithread.py not work either

**Comment by buffer** [comment]
Sorry for the very late response but this a very busy period for me.

I was aware of the threading issue and that's the reason why some tests are currently disabled. 

By the way I tested your code and can reproduce the issue using version 8.9.225.25 but the problem just disappears using version 9.2.230.21. Can you please give it a try using more recent STPyV8 releases and let me know what you observe?

Thanks!

**Comment by RonaldinhoL** [comment]
ok, i use it in windows, i will compile a new version and test it

**Comment by RonaldinhoL** [comment]
v9.0.257.29 also the same problem, i remember, i did't compile success on windows before, this issue was test on ubuntu :)

**Comment by RonaldinhoL** [comment]
when i set  DISTUTILS_DEBUG=1, it show 

distutils.errors.CompileError: command ['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\bin\\HostX86\\x64\\cl.exe', '/c', '/nologo', '/Ox', '/W3', '/GL', '/DNDEBUG', '/MD', '-DBOOST_PYTHON_STATIC_LIB', '-IE:\\xxx\\ref_project\\v8\\v8\\include', '-ID:\\local\\boost_1_76_0', '-IC:\\Users\\Ronaldinho\\.pyenv\\pyenv-win\\versions\\3.9.0\\include', '-IC:\\Users\\Ronaldinho\\.pyenv\\pyenv-win\\versions\\3.9.0\\include', '-IC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\ATLMFC\\include', '-IC:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29333\\include', '-IC:\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um', '-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt', '-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\shared', '-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\um', '-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\winrt', '-IC:\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\cppwinrt', '-ID:\\local\\boost_1_76_0', '/EHsc', '/Tpsrc\\Engine.cpp', '/Fobuild\\temp.win-amd64-3.9\\Release\\src\\Engine.obj', '/O2', '/GL', '/MT', '/EHsc', '/Gy', '/Zi'] failed with exit code 2

**Comment by buffer** [comment]
Ah ok I thought you were successful in compiling previous releases on Windows and I was going to ask to share the steps you took to do that. PyV8 used to support Windows but I never tested STPyV8 on such platform. I would really like to automate Windows builds through Github Actions too so please feel free to share any ideas and tips

**Comment by RonaldinhoL** [comment]
i try to compile in VisualStudio, got something wrong similarly, it show error was in v8.h, i guess really reason was not, maybe just a simple issue cause it stop compile, sorry i am not  familiar with c++.
![image](https://user-images.githubusercontent.com/1797392/129368033-22bfe4e7-db68-469d-a2dd-1b0c533170b3.png)

**Comment by RonaldinhoL** [comment]
> Ah ok I thought you were successful in compiling previous releases on Windows and I was going to ask to share the steps you took to do that. PyV8 used to support Windows but I never tested STPyV8 on such platform. I would really like to automate Windows builds through Github Actions too so please feel free to share any ideas and tips

yeah i once thought i compile success on windows too, when i meet the error again i rember not ...
