### ISSUE TITLE
Save a snapshot and use it later

### ISSUE THREAD

**Issue by thelinuxlich** [cloudflare/stpyv8#29]
Is it possible?

**Comment by buffer** [comment]
No, it's not possible right now. STPyV8 is a fork of PyV8. And when we started porting it to the most recent versions of V8 and Python one of our design goals was STPyV8 has to be simple. This is the reason why some PyV8 features (especially the ones that did not make use of the official API) were dropped too. By the way please let us know about the scenarios this feature could be useful and we will consider a potential implementation. Thanks

**Comment by thelinuxlich** [comment]
I don't know how worthy performance-wise it would be, but I was thinking of using Redis Gears, which runs Python functions inside a Redis Database and I needed the ability to run custom javascript inside it, so I thought about STPyV8. I thought creating a snapshot and loading from it every time instead of requiring the JS libraries would be faster.

**Comment by buffer** [comment]
I think it's worth trying. FYI right now STPyV8 is built with the snapshot support disabled. But you can easily enable it by modifying gn_args through the file settings.py (the args you need are _v8_use_external_startup_data_ and _v8_use_snapshot_. I never did that but I think you can probably generate the snapshot using mksnapshot and then let STPyV8 load it. And this is potentially interesting documentation in case you need additional details

https://github.com/danbev/learning-v8/blob/master/notes/snapshots.md
