### ISSUE TITLE
Amazonlinux2 build

### ISSUE THREAD

**Issue by mattfysh** [cloudflare/stpyv8#57]
I'm working on deploying stpyv8 to an AWS environment (restricted to amazonlinux2), and have not yet been able to get stpyv8 running. When I use the prebuilt linux whl, it throws an error because libboost cannot be found. So now I'm trying to build from source in the `amazonlinux:2` container, and here's where I'm at:

```
yum groupinstall "Development Tools"
yum install python3 python3-devel boost-devel
git clone https://github.com/cloudflare/stpyv8
cd stpyv8
python3 setup.py build
```

Receiving the following error:

```
src/Isolate.cpp: In static member function ‘static boost::python::api::object CIsolate::GetCurrent()’:
src/Isolate.cpp:69:74: error: no matching function for call to ‘shared_ptr_to_python<CIsolate>(std::shared_ptr<CIsolate>)’
                                        CIsolatePtr(new CIsolate(isolate)))));
                                                                          ^
In file included from /usr/include/boost/python/converter/arg_to_python.hpp:15:0,
                 from /usr/include/boost/python/call.hpp:15,
                 from /usr/include/boost/python/object_core.hpp:14,
                 from /usr/include/boost/python/args.hpp:25,
                 from /usr/include/boost/python.hpp:11,
                 from src/Utils.h:61,
                 from src/Exception.h:12,
                 from src/Isolate.h:4,
                 from src/Context.h:6,
                 from src/Isolate.cpp:1:
```

Will a build for this platform will be possible? For context, I am deploying to AWS Glue and planning to use st-pyv8 during an ETL job to transform the data using a snippet of custom javascript written by users.

Cheers! :)

**Comment by buffer** [comment]
Quick question. Have you installed boost dependencies? Building on Ubuntu and Debian distros requires this extra step before building

`$ sudo apt install python3 python3-dev build-essential libboost-dev libboost-system-dev libboost-python-dev libboost-iostreams-dev`

as these dependencies are not installed automatically and you are supposed to take care of it

**Comment by mattfysh** [comment]
Hi @buffer thanks for the reply. I'm running the commands from my initial comment, which does include installing `boost-devel`. To run through the dependencies in your command:

* `python3 python3-dev` - installed on line 2
* `build-essential` - installed on line 1
* `libboost-dev libboost-system-dev libboost-python-dev libboost-iostreams-dev` - installed on line 2

This results in the installation of all the boost libraries - see the dependencies list at this page
 https://amazonlinux.pkgs.org/2/amazonlinux-core-x86_64/boost-devel-1.53.0-27.amzn2.0.5.x86_64.rpm.html

**Comment by buffer** [comment]
Hi @mattfysh, no problem. Please let me know if that fixes the issue. Thanks!

**Comment by mattfysh** [comment]
Seems to be some confusion here, I just repeated the steps in the original comment we're installing dependencies

The error still remains. You can verify by re-reading the first comment and running those commands in an Amazon Linux container.

Or do you not support Amazon Linux because aws competes with cloudflare?

**Comment by buffer** [comment]
I have not a Amazon Linux container handy to further investigate but I am noticing just now that the boost library version you installed (1.53.0) is very outdated and this could explain what you're experiencing. Can you try figuring out if a more recent version can be installed some way?
