### ISSUE TITLE
Publish to pypi

### ISSUE THREAD

**Issue by almahdi404** [cloudflare/stpyv8#69]
Can it be published to **PYPI**?
It would be very helpful.

**Comment by buffer** [comment]
The problem is that STPyV8 build workflow builds Google V8 (C++) from source and makes use of the boost library which is installed by default on each selected platform. For this reason releasing a universal wheel on PyPi would be extremely hard (impossible?) at the moment

**Comment by almahdi404** [comment]
Can't it be published for linux at least?
