### ISSUE TITLE
Building from source on macOS Ventura v13.4 fails due to compilation errors

### ISSUE THREAD

**Issue by seidnerj** [cloudflare/stpyv8#74]
This is list of unique errors I am getting when trying to build from source using Apple clang version 14.0.3 (clang-1403.0.22.14.1).

error: '__abi_tag__' attribute only applies to structs, variables, functions, and namespaces
error: call to 'hypot' is ambiguous
error: expected ';' at end of declaration list
error: field has incomplete type 'std::exception_ptr'
error: member 'nullptr_t' declared as a template
error: no member named 'nullptr_t' in the global namespace
error: no template named '__promote'
error: non-static data member cannot be constexpr; did you intend to make it const?
error: template argument for template type parameter must be a type
error: unknown type name 'nullptr_t'
error: use of undeclared identifier '__promote'
error: use of undeclared identifier 'nullptr_t'; did you mean 'nullptr'?

I tried setting CFLAGS=-std=c++ in the terminal session before running pip install but it did not make a difference. I also tried setting export CFLAGS="-stdlib=libc++ -std=c++14" with the same result.

Any help would be appreciated, thanks.

**Comment by buffer** [comment]
I really suggest you not to waste time and efforts compiling STPyV8 by yourself if you're planning to use it on macOS as we already automated these steps using Github Actions. If you take a look at https://github.com/cloudflare/stpyv8/releases you'll realize that Python binary wheels are provided for a few platforms. In your case you should use the wheel named stpyv8-macos-12-python-3.11. On macOS Ventura

1. install boost-python3 using brew
2. unzip the release file
3. copy the file icudtl.dat to the folder /Library/Application Support/STPyV8 (create the folder if necessary)
4. pip install <wheel file>

**Comment by seidnerj** [comment]
I would, only I have two issues with that approach:
1. When I try to install it that way I get a "symbol not found" error during import (I assume this is because I am running macOS 13 and not 12?):
>>> import STPyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/PycharmProjects/project/venv/lib/python3.11/site-packages/STPyV8.py", line 10, in <module>
    import _STPyV8
ImportError: dlopen(/Users/user/PycharmProjects/project/venv/lib/python3.11/site-packages/_STPyV8.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN2v82V87DisposeEv'
2. I will also need to install this on production machines where I don't have access run an installer that way, only via requirements.txt, but this is not available on PyPi.

Suggestions?

Thanks in advance!

**Comment by buffer** [comment]
1. I use STPyV8 on macOS 13 and never experienced that issue. Just a question. Have you correctly installed boost-python3 (brew install boost-python3) and is it importable from the venv? I suspect that using the flag --system-site-packages while creating your venv is all you need to fix the issue
2. Not entirely clear to me. You just need pip to install the Python binary wheel. Am I missing something?

**Comment by seidnerj** [comment]
1. I did install boost-python3 using brew, without any issues. I will try using the flag you suggested.
2. The only control I have in this scenario is changing requirements.txt file, the wheel file is not hosted anywhere currently as far as I could tell (only the zip file that includes it is hosted on Github) and so I would have to host it somewhere myself, but still I wouldn't be able to make the changes the operating system, i.e. copying icudtl.dat to the suggested location.

**Comment by buffer** [comment]
WRT 2. please take a look at [1] as this suggests a way to automate STPyV8 installation using the released wheels. This excerpt runs on Linux but it should be quite easy to adapt to macOS

[1] https://github.com/buffer/thug/blob/master/tox.ini

**Comment by seidnerj** [comment]
I just tried recreating env with the flag you suggested, unfortunately the result is the same:

```
~/Project ❯❯❯ python -m venv venv --system-site-packages
~/Project ❯❯❯ source venv/bin/activate
(venv) ~/P/~/Project ❯❯❯ pip install --upgrade pip
Requirement already satisfied: pip in ./venv/lib/python3.11/site-packages (22.3.1)
Collecting pip
  Using cached pip-23.1.2-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 22.3.1
    Uninstalling pip-22.3.1:
      Successfully uninstalled pip-22.3.1
Successfully installed pip-23.1.2
(venv) ~/P/~/Project ❯❯❯ pip install -r requirements.txt
Processing ./stpyv8-11.4.183.17-cp311-cp311-macosx_10_9_universal2.whl (from -r requirements.txt (line 3))
Installing collected packages: stpyv8
Successfully installed stpyv8-11.4.183.17
(venv) ~/P/~/Project ❯❯❯ python
Python 3.11.3 (main, Apr 27 2023, 18:33:05) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import STPyV8
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/User/Projects/Project/venv/lib/python3.11/site-packages/STPyV8.py", line 10, in <module>
    import _STPyV8
ImportError: dlopen(/Users/user/Projects/Project/venv/lib/python3.11/site-packages/_STPyV8.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN2v82V87DisposeEv'
```

**Comment by seidnerj** [comment]
> WRT 2. please take a look at [1] as this suggests a way to automate STPyV8 installation using the released wheels. This excerpt runs on Linux but it should be quite easy to adapt to macOS
> 
> [1] https://github.com/buffer/thug/blob/master/tox.ini

Thanks! I'll take a look!

**Comment by seidnerj** [comment]
I think I found the issue, take a look in the link below and let me know what you think:
https://stackoverflow.com/questions/35006614/what-does-symbol-not-found-expected-in-flat-namespace-actually-mean

**Comment by seidnerj** [comment]
I am trying to install boost using brew while rebuilding it from source using libstdc++ instead of libc++, if this succeeds and solves the above issue, I will post instructions on how to do that.

**Comment by seidnerj** [comment]
So.. this led me down a very deep rabbit hole, until I unfortunately got stuck. Compiling boost using libc++ on macOS is easy peasy but trying to compile with libsdtc++ results in compilation errors which are not obvious to resolve. Honestly, it seems compiling STPyV8 using libc++ (instead of compiling boost using libsdtc++, if that is even the problem) should be an easier solve.

**Comment by buffer** [comment]
A suggestion. You should really try pyenv [1]. This would make everything super easy on your side

[1] https://github.com/pyenv/pyenv

**Comment by seidnerj** [comment]
I am already using pyenv 😬
