### ISSUE TITLE
Ubuntu 20.04 with Python 3.10

### ISSUE THREAD

**Issue by dsetzer** [cloudflare/stpyv8#81]
Why is there no release for this included? That is the default environment of github codespaces and would be nice to have..

**Comment by buffer** [comment]
The issue that prevents from releasing a wheel for Ubuntu 20.04 - Python 3.10 environment is mainly related to boost-python. 

FYI Python 3.10 ABI is not compatible with Python < 3.10 ABI. This means that boost-python package built with Python 3.9 can be used with Python 3.8 but not with Python >3.10. When I used to generate wheels for Ubuntu 18.04 I used this compatibility to generate wheels for Python 3.6, 3.7, 3.8 and 3.9 starting from a single installed package. If you try using the same package with Python 3.10 all you get is a segmentation fault at runtime. Moreover consider that I use boost and boost-python as packaged by Ubuntu and do not try recompiling them from scratch as it will take very long time. And that's the reason why such wheel is not currently available.

**Comment by baseplate-admin** [comment]
Hi, is boost-python is the issue maybe we can generate a wheel file for each python version? This seems to be the [approach taken by `Pillow`
](https://pypi.org/project/Pillow/#files)
![image](https://github.com/cloudflare/stpyv8/assets/61817579/bf34a52a-9561-4faf-b0e5-73e285198744)

**Comment by baseplate-admin** [comment]
Investigating deeper, i think it's better to use `pybind11`. It [produces binaries significantly smaller](https://graylab.jhu.edu/Sergey/2016.RosettaCon/PyRosetta-4.pdf) than `Boost.Python`

**Comment by buffer** [comment]
@baseplate-admin FYI I am currently working to generate Python wheels for different versions of Python on different platforms. The idea is to host them on PyPI once the effort will be completed. Unfortunately it's not that straightforward so it is taking way more time and effort than I expected

**Comment by buffer** [comment]
UPDATE: I was able to build a few manylinux_2_31 wheel which supports the most recent Linux distributions (including Ubuntu 20.04) on Python 3.9, 3.10, 3.11 and 3.12. The wheel statically includes boost and boost-python so installing them on the end user system is not required anymore. Moreover the ICU data file is included in the wheel itself and copying it at a specific path is not required anymore. The same approach was used for OSX and Windows wheels.

I would really appreciate if you could take some time to test it on your systems and report any potential issue. The mostly recent built Linux wheels can be downloaded from [1]. Once I will be confident they work on every platform I will upload them to PyPI thus making the installation experience extremely simple.

CC @dsetzer @baseplate-admin @agrover 

[1] https://github.com/cloudflare/stpyv8/actions/runs/7384344827
