### ISSUE TITLE
Windows Wheel for Python 3.12

### ISSUE THREAD

**Issue by SamG101-Developer** [cloudflare/stpyv8#96]
Would it be possible for a Windows wheel file to be provided for Python 3.12, please?

**Comment by buffer** [comment]
I just created a patch to generate a Python 3.12 wheel for Windows. If you want to test it soon just refer to the artifacts at

https://github.com/cloudflare/stpyv8/actions/runs/7847635999

The wheel will be automatically uploaded to PyPI at the next STPyV8 release
